-- 1. Basic customer behaviour
-- Number of unique customers
SELECT DISTINCT
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM
	CUSTOMERS;

-- Number of order per customers
SELECT
	CUSTOMER_ID,
	COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM
	ORDERS
GROUP BY
	CUSTOMER_ID;

-- Average review score per customer
SELECT
	O.CUSTOMER_ID,
	ROUND(AVG(R.REVIEW_SCORE), 2) AS AVERAGE_REVIEW_SCORE
FROM
	ORDERS O
	JOIN ORDER_REVIEW R ON O.ORDER_ID = R.ORDER_ID
GROUP BY
	O.CUSTOMER_ID;

-- Payment method behaviour
SELECT
	P.PAYMENT_TYPE AS PAYMENT_METHOD,
	COUNT(O.CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM
	ORDER_PAYMENTS P
	JOIN ORDERS O ON P.ORDER_ID = O.ORDER_ID
GROUP BY
	PAYMENT_METHOD
ORDER BY
	TOTAL_CUSTOMERS DESC;

-- 2. Spending behaviour
-- Total and average payment per order
SELECT
	ORDER_ID,
	SUM(PAYMENT_VALUE) AS TOTAL_PAYMENT
FROM
	ORDER_PAYMENTS
GROUP BY
	ORDER_ID;

-- Total spending per customer
SELECT
	O.CUSTOMER_ID,
	SUM(P.PAYMENT_VALUE) AS TOTAL_SPENT
FROM
	ORDERS O
	JOIN ORDER_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
GROUP BY
	O.CUSTOMER_ID
ORDER BY
	TOTAL_SPENT DESC;

-- 3. Delivery and Timelines
-- Delivery time(astimated vs actual)
SELECT
	ORDER_ID,
	ORDER_ESTIMATED_DELIVERY_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE,
	DATE (ORDER_DELIVERED_CUSTOMER_DATE) - DATE (ORDER_ESTIMATED_DELIVERY_DATE) AS DELIVERY_DELAY_DAYS,
	CASE
		WHEN DATE (ORDER_DELIVERED_CUSTOMER_DATE) - DATE (ORDER_ESTIMATED_DELIVERY_DATE) < 0 THEN 'Early'
		WHEN DATE (ORDER_DELIVERED_CUSTOMER_DATE) - DATE (ORDER_ESTIMATED_DELIVERY_DATE) > 0 THEN 'Late'
		ELSE 'On time'
	END AS DELIVERY_STATUS
FROM
	ORDERS
WHERE
	ORDER_STATUS = 'delivered';

-- Top catogories by number of orders
SELECT
	P.PRODUCT_CATEGORY_NAME AS CATEGORY,
	COUNT(O.ORDER_ID) TOTAL_ORDER
FROM
	PRODUCTS P
	JOIN ORDER_ITEMS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
	CATEGORY
ORDER BY
	TOTAL_ORDER DESC
LIMIT
	10;

-- Average order value per customer
SELECT
	O.CUSTOMER_ID,
	COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
	SUM(P.PAYMENT_VALUE) AS TOTAL_SPENT,
	ROUND(
		SUM(P.PAYMENT_VALUE) / COUNT(DISTINCT O.ORDER_ID),
		2
	) AS AVG_ORDER_VALUE
FROM
	ORDERS O
	JOIN ORDER_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
GROUP BY
	O.CUSTOMER_ID
ORDER BY
	AVG_ORDER_VALUE DESC;

-- Clustre customer behaviour
WITH
	ORDER_SUMMARY AS (
		SELECT
			O.CUSTOMER_ID,
			COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
			SUM(P.PAYMENT_VALUE) AS TOTAL_SPENT,
			ROUND(
				SUM(P.PAYMENT_VALUE) / COUNT(DISTINCT O.ORDER_ID),
				2
			) AS AVG_ORDER_VALUE
		FROM
			ORDERS O
			JOIN ORDER_PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
		GROUP BY
			O.CUSTOMER_ID
		ORDER BY
			AVG_ORDER_VALUE DESC
	),
	REVIEW_SUMMARY AS (
		SELECT
			O.CUSTOMER_ID,
			ROUND(AVG(R.REVIEW_SCORE), 2) AS AVG_REVIEW_SCORE
		FROM
			ORDERS O
			JOIN ORDER_REVIEW R ON O.ORDER_ID = R.ORDER_ID
		GROUP BY
			O.CUSTOMER_ID
	)
SELECT
	OS.CUSTOMER_ID,
	TOTAL_ORDERS,
	TOTAL_SPENT,
	AVG_ORDER_VALUE,
	AVG_REVIEW_SCORE
FROM
	ORDER_SUMMARY OS
	JOIN REVIEW_SUMMARY RS ON OS.CUSTOMER_ID = RS.CUSTOMER_ID;

-- Seller with most delayed orders
WITH SELLERS_BEHAVIOUR AS (
    SELECT
        S.SELLER_ID,
        EXTRACT(DAY FROM O.ORDER_DELIVERED_CUSTOMER_DATE - O.ORDER_ESTIMATED_DELIVERY_DATE) AS DELAYED_DAYS,
        CASE
            WHEN O.ORDER_DELIVERED_CUSTOMER_DATE > O.ORDER_ESTIMATED_DELIVERY_DATE THEN 'Late'
            WHEN O.ORDER_DELIVERED_CUSTOMER_DATE < O.ORDER_ESTIMATED_DELIVERY_DATE THEN 'Early'
            ELSE 'On time'
        END AS DELIVERY_STATUS
    FROM
        ORDERS O
        JOIN ORDER_ITEMS OI ON OI.ORDER_ID = O.ORDER_ID
        JOIN SELLERS S ON OI.SELLER_ID = S.SELLER_ID
)
SELECT
    SELLER_ID,
    COUNT(*) AS TOTAL_DELAYED_ORDERS
FROM
    SELLERS_BEHAVIOUR
WHERE
    DELIVERY_STATUS = 'Late'
GROUP BY
    SELLER_ID
ORDER BY
    TOTAL_DELAYED_ORDERS DESC;


-- Sellers with longest delivery time
SELECT
	S.SELLER_ID,
	ROUND(
		AVG(
			EXTRACT(
				DAY
				FROM
					(
						O.ORDER_DELIVERED_CUSTOMER_DATE - O.ORDER_ESTIMATED_DELIVERY_DATE
					)
			)
		),
		2
	) AS AVG_DELAY_DAYS
FROM
	ORDERS O
	JOIN ORDER_ITEMS OI ON OI.ORDER_ID = O.ORDER_ID
	JOIN SELLERS S ON OI.SELLER_ID = S.SELLER_ID
WHERE
	O.ORDER_STATUS = 'delivered'
GROUP BY
	S.SELLER_ID
ORDER BY
	AVG_DELAY_DAYS DESC
LIMIT
	10;

